# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  NODE_ENV: "Production"
  MAX_RETRIES: 3

trigger:
- master

schedules:
- cron: "0 */6 * * *"
  displayName: Hourly build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: NodeTool@0
  displayName: "Use Node 10.x"
  inputs:
    versionSpec: 10.x
    checkLatest: true

- task: Npm@1
  displayName: "npm install"
  inputs:
    workingDir: ./
    verbose: false

- task: Npm@1
  displayName: "npm run"
  inputs:
    command: custom
    workingDir: ./
    verbose: false
    customCommand: "run pipeline"

- task: CopyFiles@2
  displayName: "Copy files"
  inputs:
    Contents: |
      **/logs/**
      **/floodTests/tmp/**

    TargetFolder: "$(Build.ArtifactStagingDirectory)"
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  displayName: "Publish artifacts"
  inputs:
    targetPath: "$(Build.ArtifactStagingDirectory)"
    artifact: deploy
  condition: succeededOrFailed()
